---
# tasks file for hosts

- name: Set hostname
  hostname:
    name: "{{ hosts_hostname }}.{{ hosts_domain }}"
  become: yes
  when: hosts_hostname is defined

- name: Set hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  become: yes
  when: hosts_hostname is defined
